gui:
  showIcons: true
  theme:
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # White / Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#89b4fa" # Blue, set to `default` to have no background colour
    selectedRangeBgColor:
      - "#89b4fa" # Blue
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - "#f38ba8" # Red
    defaultFgColor:
      - default
