[glyph]
left  = 
right = 
sepLeft = 
sepRight = 

;================================================================================
;
[module/a]
type = custom/text
content-foreground = ${color.a}
content-background = ${color.b}
content = ${glyph.left}
content-font = 2

[module/b]
type = custom/text
content-foreground = ${color.b}
content-background = ${color.bg0}
content = ${glyph.left}
content-font = 2

[module/sepLeft]
type = custom/text
content-foreground = ${color.fg}
content-background = ${color.bg0}
content = ${glyph.sepLeft}
content-font = 2

;================================================================================

[module/w]
type = custom/text
content-background = ${color.bg0}
content-foreground = ${color.w}
content = ${glyph.right}
content-font = 2

[module/x]
type = custom/text
content-background = ${color.w}
content-foreground = ${color.x}
content = ${glyph.right}
content-font = 2

[module/y]
type = custom/text
content-background = ${color.x}
content-foreground = ${color.y}
content = ${glyph.right}
content-font = 2

[module/z]
type = custom/text
content-background = ${color.y}
content-foreground = ${color.z}
content = ${glyph.right}
content-font = 2

[module/sepRight]
type = custom/text
content-foreground = ${color.fg}
content-background = ${color.bg0}
content = ${glyph.sepRight}
content-font = 2
