palette = "catppuccin_mocha"

format = """
[](fg:green)$os\
$username[](fg:green bg:flamingo)\
$hostname[](fg:flamingo bg:maroon)\
$git_branch$git_status[](fg:maroon bg:mauve)\
$directory[](fg:mauve)\
$fill\
[](fg:blue)$conda\
[](fg:yellow bg:blue)$rust\
[](fg:pink bg:yellow)$time[](fg:pink)
$character
"""

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
disabled = false
format = "[$symbol]($style)"
style = "fg:base bg:green"

[os.symbols]
Arch = " "
Ubuntu = " "
Windows = " "

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
disabled = false
show_always = true
format = "[$user]($style)"
style_user = "fg:base bg:green"
style_root = "fg:mantle bg:green"

[hostname]
ssh_only = true
format = "[$hostname]($style)"
style = "fg:base bg:flamingo"

[directory]
format = "[ $path ]($style)"
style = "fg:base bg:mauve"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:base bg:maroon"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "fg:base bg:maroon"
format = "[$all_status$ahead_behind ]($style)"

[fill]
symbol = " "

[conda]
format = "[ $symbol$environment ]($style)"
style = "fg:base bg:blue"
symbol = " "

[rust]
style = "fg:base bg:yellow"
format = "[$symbol$version ]($style)"
symbol = "[](fg:red bg:yellow) "

[time]
disabled = false
time_format = "%R"             # Hour:Minute Format
style = "fg:base bg:pink"
format = "[  $time ]($style)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
